apiVersion: v1
kind: Service
metadata:
  name: notification-postgres
  namespace: microservices
spec:
  selector:
    app: notification-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
