apiVersion: v1
kind: Service
metadata:
  name: transaction-postgres
  namespace: microservices
spec:
  selector:
    app: transaction-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
