apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: microservices
data:
  NOTIFICATION_SERVICE_DATABASE_URL: "postgresql://postgres:password@notification-postgres:5432/notification_service_db"