apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: microservices
data:
  ACCOUNT_SERVICE_DATABASE_URL: "postgresql://postgres:password@account-postgres:5432/account_service_db"
