apiVersion: v1
kind: Service
metadata:
  name: account-postgres
  namespace: microservices
spec:
  selector:
    app: account-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
